Fix compile error on OPENSSL_VERSION_MAJOR < 3
../pdns/libssl.cc:637:28: error: no member named 'content' in 'OpenSSLTLSTicketKey'

(cherry picked from commit b1f09edc04813ecb9e70f17834ad9796432201cd)