include errno
to avoid:
     File "/__w/pdns/pdns/regression-tests.recursor-dnssec/test_RecDnstap.py", line 189, in FrameStreamUnixListener
        if e.errno in (errno.EBADF, errno.EPIPE):
     NameError: name 'errno' is not defined