Stringify preprocessor string
When compiling with something like './configure
CXXFLAGS=-DPACKAGEVERSION="1.2.3"', we fail with
"../config.h:162:792: error: too many decimal points in number"

This happens because the string as defined in config.h
has embedded double quotes. Escape them.