dnsdist: Fix compilation by adding a missing <optional> include in misc.cc
Otherwise g++ 11.2.0 complains here:
```
misc.cc: In function ‘int makeIPv6sockaddr(const string&, sockaddr_in6*)’:
misc.cc:711:8: error: ‘optional’ is not a member of ‘std’
  711 |   std::optional<uint16_t> port = std::nullopt;
      |        ^~~~~~~~
misc.cc:61:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
```