dnsdist: re-add missing libsodium include
After commit 415a18aa0563 libsodium's sodium_init() went missing in certain
build configurations:

../dnsdist-9999/pdns/dnsdistdist/dnsdist.cc: In function 'int main(int, char**)':
../dnsdist-9999/pdns/dnsdistdist/dnsdist.cc:1327:9: error: 'sodium_init' was not declared in this scope
 1327 |     if (sodium_init() == -1) {
      |         ^~~~~~~~~~~

This adds it back.

Signed-off-by: Holger Hoffstätte <holger@applied-asynchrony.com>