Fix use of BOOST_CHECK_MESSAGE in test-dnsrecords_cc.cc
BOOST_CHECK_MESSAGE is designed to take a statement that describes a condition.

When `-l all` is used, it will print the statement, the condition, and
whether or not the condition passed.

With this change, output can appear like this:
test-dnsrecords_cc.cc:72: error: in "test_dnsrecords_cc/test_record_types": record types should be sorted such that 13 >= 21
Checking record type HINFO test #1
test-dnsrecords_cc.cc:72: info: check 'record types should be sorted such that 13 >= 13' has passed