Dnsdist: Fix build failure on FreeBSD
YaHTTP needs Boost headers, and those are in /usr/local/include on FreeBSD.

Append BOOST_CPPFLAGS to AM_CPPFLAGS in configure.ac, so every Makefile uses them.
Also set the compiler flags globally, so that we compile yahttp with the same settings.

Fixes "/reqresp.hpp:7:10: fatal error: 'boost/function.hpp' file not found"