pdnsexception: Stop importing various namespaces
Signed-off-by: Remi Gacogne <remi.gacogne@powerdns.com>
(cherry picked from commit 911b73e58f3719b2fa520fc82284e65bcd0d15cb)