dnsdist: Add missing `stdexcept` include in `lmdb-safe.hh`
It was only included for non-dnsdist contexts, but `std::runtime_error`
is used in all contexts and gcc version 14.2.1 20240910 (at least) is
not happy about it:
```
In file included from ext/lmdb-safe/lmdb-safe.cc:2:
ext/lmdb-safe/lmdb-safe.hh: In member function ‘int MDBROTransactionImpl::get(MDB_dbi, const MDBInVal&, MDBOutVal&)’:
ext/lmdb-safe/lmdb-safe.hh:379:18: error: ‘runtime_error’ is not a member of ‘std’
  379 |       throw std::runtime_error("Attempt to use a closed RO transaction for get");
      |
```