LuaWrapper: Throw instead of asserting for null objects
LuaWrapper used to throw when a NULL object was passed to a method
or accessor binding. Unfortunately it is not always possible from
the Lua side to ensure that a userdata object is not a NULL one,
so terminating the process on such an error is not nice.

For example in dnsdist, this turns calling the `setUp` method on
an invalid (NULL) backend `DownstreamState` from:
```
dnsdist: ./ext/luawrapper/include/LuaContext.hpp:1155: auto LuaContext::registerFunctionImpl(const std::string &, std::_Mem_fn<void (DownstreamState::*)()>, tag<DownstreamState>, tag<void ()>)::(anonymous class)::operator()(const std::shared_ptr<TObject> &, TOtherParams...) const: Assertion `obj' failed.
Aborted (core dumped)
```
to:
```
Error: [string "a = getServer("..."]:1: Caught exception: Calling method setUp on a NULL object of type 15DownstreamState
stack traceback:
	[C]: in function 'setUp'
```